# Generated by Django 4.2.4 on 2024-03-10 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0010_auto_20200305_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('post', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField(max_length=1000)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'FB_Comment',
            },
        ),
    ]
