# Generated by Django 5.0.3 on 2024-03-24 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0011_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cust',
            name='Address',
            field=models.CharField(default='', max_length=50),
        ),
    ]
