# Generated by Django 5.0.3 on 2024-03-31 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0012_alter_comment_body_alter_comment_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(default='0'),
        ),
    ]
